### ISSUE TITLE
Only send changes across state message channels

### ISSUE THREAD

**Issue by tshaddix** [tshaddix/react-chrome-redux#12]
@viskin suggested in #10 that sending full state objects for every store change can become costly as the state size grows. One solution is to only send changes over the message channel.

**Comment by vhmth** [comment]
In Opentest's Chrome extension, we send updates of the audio stream frequency data if our audio visualizer bar is showing in the UI.

<img width="398" alt="screen shot 2016-08-09 at 10 51 00 am" src="https://cloud.githubusercontent.com/assets/603426/17527158/0ffb7074-5e1f-11e6-935a-4bb087020dad.png">

The delta of the state is small (just one byte array of length the number of bars in the visualizer), but the updates are very frequent. Just leaving this here for myself so I can look at the performance impact from the dev console to see how the following two things are impacted as the state size grows/shrinks:

1. Serializing/deserializing the state.
2. Latency of sending the state over the port object.

We should actually make sure that diff-ing the object makes sense and doesn't itself introduce unnecessary overhead. The reason it works for react to diff DOM updates is because the DOM itself is slow. We simply have to validate that here with larger messages over the port object.

**Comment by tshaddix** [comment]
Sounds like a great test case. Looking forward to seeing the results.

I couldn't agree more with you. We definitely shouldn't implement this willy-nilly. We should test this proposal against multiple use cases (frequency and state size).

**Comment by sidoruk-sv** [comment]
Found some analog for this:
https://github.com/ivantsov/redux-webext

**Comment by tshaddix** [comment]
@sidoruk-sv Do you mind expanding on your comment a bit more? From what I can tell, that package uses the [same method](https://github.com/ivantsov/redux-webext/blob/master/src/background-store.js#L44) as `react-chrome-redux`.

**Comment by sidoruk-sv** [comment]
@tshaddix oh, I see, thought they implement lightweight messages, but now I see that it's very similar to this library, i'm sorry)
Will try to use your library for my pet project. Thank you!)

**Comment by vhmth** [comment]
@sidoruk-sv if you'd like to see an extension in the wild that uses this library, check out the Openvid extension:

https://chrome.google.com/webstore/detail/openvid-screen-recorder-c/liecbddmkiiihnedobmlmillhodjkdmb

**Comment by tshaddix** [comment]
Included in #100
