### ISSUE TITLE
Retrieving initiator info from popup

### ISSUE THREAD

**Issue by ericalli** [tshaddix/react-chrome-redux#130]
I have a popup component that dispatches an action upon clicking a link within it. In my reducer, I'm attempting to store the associated tabId in which the popup was clicked from. However it looks as though the _sender object differs whether its sent form a popup vs. content script. For example:

**_sender object from popup**

![screen shot 2018-02-12 at 6 53 12 am](https://user-images.githubusercontent.com/13506/36102518-69bf9248-0fc1-11e8-8b50-fe584d2921cf.png)

**_sender object from content script**

![screen shot 2018-02-12 at 6 55 02 am](https://user-images.githubusercontent.com/13506/36102607-b0e0dcc2-0fc1-11e8-9165-41bb895a9322.png)

As you can see, the "tab" object is missing entirely when the action originates form the popup script. Is there anyway to access the tabId from a popup?

Ultimately I'd like to get this working so I can use the [tab identifier utility](https://github.com/tshaddix/chrome-tab-identifier).

**Comment by tshaddix** [comment]
@ericalli Makes sense! The go-to way this is usually solved is by just grabbing the current active tab in your background/event page when an action comes through via popup:

```js
chrome.tabs.query({active: true, currentWindow: true}, function(tabs) {
  var currTab = tabs[0];
  if (currTab) { // Sanity check
    /* do stuff */
  }
});
``

Will this work for you?

**Comment by vhmth** [comment]
@ericalli to expand on @tshaddix's point a bit more, the reason this happens is because Chrome is likely not giving us this info. We always try to send the sender:

https://github.com/tshaddix/react-chrome-redux/blob/master/src/wrap-store/wrapStore.js#L109

I guess it makes sense that we grab this info from within `wrapStore` just to maintain consistency in the API, but it might introduce quite a bit of latency if with updates to the store if there are many of them.
