### ISSUE TITLE
Question: How to get the current tab id / info in the content script?

### ISSUE THREAD

**Issue by rvenugopal** [tshaddix/react-chrome-redux#57]
Hi

My scenario is that I am tracking a context menu click on selected text. I need to inform only the current tab to perform subsequent action.

I can use https://github.com/tshaddix/react-chrome-redux#4-optional-retrieve-information-about-the-initiator-of-the-action but this broadcasts the tab information to all tabs.  Is there some way in react-chrome-redux to compare this or do I need to track the current tab using 

```
chrome.tabs.onUpdated.addListener
```

Thanks
RV

**Comment by vhmth** [comment]
Hey @rvenugopal 👋🏾. Could you expand on what you mean by "tracking a context menu click on selected text". What does the "selected text" portion of that mean? And what is the "subsequent action" that must be performed? If that action must be performed only within a certain tab, you will need to store that tab ID in your state for when it gets updated and sent to your content script (where I'm assuming the "subsequent action" takes place). Right now I don't really have a good grasp on what your situation is.

**Comment by tshaddix** [comment]
@rvenugopal I don't claim to have the best solution for getting a tabId on the content script, but I did write something for a little extension that does this.

On the background, I had this:

https://github.com/tshaddix/next-read/blob/master/event/src/lib/tab-identifier/index.js

And on the content script, I had this:

https://github.com/tshaddix/next-read/blob/master/content-script/src/scripts/lib/tab-identifier-client/index.js

Finally, in the content script, I had this in my root App component.

https://github.com/tshaddix/next-read/blob/master/content-script/src/scripts/components/app/App.jsx#L25

That way, I could just filter properties on the store state by that `tabId`.

Not sure if that's helpful, but it's what immediately came to mind.

**Comment by rvenugopal** [comment]
Great.  Thanks @vhmth and @tshaddix for your responses. 

The reasons for asking was I am trying to maintain page specific state in the store.  The actions are driven by the contextMenu (which is registered in the background page and contains the tab info).  However, since the store would broadcast the updates to all tabs,  I would have to filter the updates on the content script if I wanted page specific state.

From my testing, all content script instances are receiving the update (at least for actions driven by context menu).

@tshaddix I will try out your code this evening 

Thanks
RV

**Comment by vhmth** [comment]
@rvenugopal yep that filtering will need to happen in the content scripts unfortunately. This is because the redux idiom is that all applications have the *same* state so that reasoning about application logic is easier. I agree that this filtering logic is specific per something like an extension, but I believe that sending updates with the whole state of the store avoids side-effecty issues down the road from people trying to be too smart.

**Comment by rvenugopal** [comment]
@tshaddix Thanks for the code samples.  They work a peach.  Much appreciated.

@vhmth Thanks for the explanation

**Comment by rvenugopal** [comment]
@tshaddix Yes, please close the issue

**Comment by shastings517** [comment]
@tshaddix @vhmth I love this library and have been using it a ton, it has been a huge help in making redux/react work with the extension I am developing. I am currently running into the same issue as rvenugopal, I need to figure out some way to filter store content by tabId in my content scripts so that an action is only performed in the current tab and not all of them at once. Unfortunately it looks like the repo that you had previously linked is no longer on github. Is there any way I could take a look at your solution to this issue? Any help would be much appreciated

**Comment by tshaddix** [comment]
Hi @shastings517 ! Does this help?

https://github.com/tshaddix/chrome-tab-identifier

**Comment by shastings517** [comment]
@tshaddix hahaa yes it does! Exactly what i was looking for. Thanks so much
