### ISSUE TITLE
support for non-immutable store?

### ISSUE THREAD

**Issue by DeDuckProject** [tshaddix/react-chrome-redux#62]
Hi,
So we have a store that's totally non-immutable. We are using parse-server, so our store actually contains many parse object, which are essentially an object with function that cannot be serialize..
As my understanding of this module, it works by sending the store update with json messages. Upon sending these messages I get some errors which (I think) are a result of trying to form a JSON object from these objects which are not meant for that.

My question is basically if anyone has encountered such behaviour, or if you are aware of a workaround.

I cannot afford to change my store to be immutable, as this will require too much unwanted changes with the entire logic of the original web app - which we wanted to reuse its components.

Another option would be to fork this repo and change the messaging logic, but I'm not sure if even then it would be possible.

Would love to hear your insights about this one!

Cheers,
IY

**Comment by vhmth** [comment]
@DeDuckProject in the Redux world, it's considered bad practice to store unserializable objects in your store. Your issue is not one with immutability - it's with serializability. What do these parse objects/functions do?

**Comment by DeDuckProject** [comment]
You are correct. My issue is definitely serializability and the distinction is an important one.

These objects are essentially a more abstract way to to represent a DB row, with some functions around it such as set, get and save.

Somewhere along the way, when turning the object into a JSON, some inner field's toJSON is fired but is undefined and I can't figure out why, but this seems like a serialization problem.

**Comment by vhmth** [comment]
Hey man sounds like you definitely want these objects serialized to your store. Sounds like you may also need to provide a `toJSON` method to your Parse objects (although I'm not sure since I've never used Parse).

Other than serializing your Parse objects to the store, I suggest you keep the actual Parse objects around in a middle layer between your store and when your actions get received on the background script. I would say the perfect area to keep these things would be in our `alias` layer. An `alias` is essentially an action creator that is guaranteed to run in the background script of your Chrome extension. You can keep your Parse objects accessible from this scope and do any updating/deleting/whatever to them before the action gets dispatched to the store on the background script.

Here's our README section on aliases:

https://github.com/tshaddix/react-chrome-redux#3-optional-implement-actions-whose-logic-only-happens-in-the-background-script-we-call-them-aliases

Also, we understand that our language around aliases can be a bit confusing at first. Take a look at the comments on this issue and see if it helps if you're still confused:

https://github.com/tshaddix/react-chrome-redux/issues/46

**Comment by vhmth** [comment]
Are you cool with me closing this issue for now? We can still comment here as you try to get this stuff to work.

**Comment by DeDuckProject** [comment]
@vhmth Thanks for the informative explanation!
Storing my Parse objects in the aliases scope is probably the most intuitive solution.
However this will require us to restructure all the components which already refer to these objects through the store. I was under the impression we could re-use them seamlessly. :(
toJSON **is** implemented for the Parse objects, but there are some problems with that from what we've seen..
My main goal basically is to keep the chrome extension components the same as the web ones, which currently make full use of the functions that come with Parse objects. I suppose we would have to keep everything in the aliases' scope and figure out what to do from there.
Closing. <3

**Comment by vhmth** [comment]
Hmm this is what I would do:

1. Create a utility that houses your Parse objects.
2. When you call that utility, it checks a conditional that's set at build time. We use [string-replace-webpack-plugin](https://github.com/jamesandersen/string-replace-webpack-plugin) to set build-time variables.
3. If the conditional is true (let's say `IS_CONTENT_SCRIPT`), then you dispatch an alias to the store, otherwise you call operations on parse objects and update the store.
