### ISSUE TITLE
[Question] Cannot applyMiddleware redux-thunk, action undefined

### ISSUE THREAD

**Issue by TerencedzLi** [tshaddix/react-chrome-redux#70]
Hello, I'm trying to apply redux-thunk to react-chrome-redux but I'm getting these errors when trying to dispatch an 'asynchronous' action:

**Error from popup.js:**
![image](https://cloud.githubusercontent.com/assets/5669145/24052248/33fe0fe2-0b0b-11e7-8496-f4f44066185b.png)

**Error from event.js (background process)**
![image](https://cloud.githubusercontent.com/assets/5669145/24052278/4bf865e8-0b0b-11e7-853b-2173772d8be5.png)

When I step through after the action gets invoked, action is undefined in createStore:
![image](https://cloud.githubusercontent.com/assets/5669145/24052509/1a9a8534-0b0c-11e7-8ae0-7186462e691a.png)

I've been trying to debug this for a while, any help would be nice!
```
// Code inside React Component to test
  componentDidMount() {
    const { actions } = this.props;
    actions.asyncCount();
  }

// actions.js
export function asyncCount () {
  return function (dispatch) {
    setTimeout(function() {
      dispatch({type: "ADD_COUNT"})
    }, 1000)
  }
}

// event.js

import {createStore, applyMiddleware} from 'redux';
import thunk from 'redux-thunk';
import rootReducer from './reducers';

import {wrapStore} from 'react-chrome-redux';
const store = createStore(rootReducer, applyMiddleware(thunk));

wrapStore(store, {
  portName: 'DRAG_NOTE'
});

**Comment by AgrimPrasad** [comment]
It's difficult to pinpoint the issue without access to the full source code. Would it be possible to provide access?

Some possible issues:

1. The portName 'DRAG_NOTE' is not used to create a proxy store in the popup component. Refer to https://github.com/AgrimPrasad/mozilla-observatory-extensions/blob/master/src/components/popup/index.jsx
2. The redux version (or the version of some other dependency) is not up to date. The syntax `const store = createStore(rootReducer, applyMiddleware(thunk));` requires redux@>=3.1.0

**Comment by TerencedzLi** [comment]
Hey @AgrimPrasad ,

Thanks for the response.

I've invited you to the repo I'm working on. Would you mind having a look if you have a chance?
I would really appreciate it!

I think that the proxyStore works as normal non-async actions work (and increase the "counter").

**Comment by TerencedzLi** [comment]
@AgrimPrasad, I've updated redux to 3.6 and redux-thunk to 2.2.0, and still no dice :/

**Comment by vhmth** [comment]
Let me know if you need another pair of eyes here @AgrimPrasad!

**Comment by AgrimPrasad** [comment]
Hey guys, I only took a brief look at the code this morning, and I suspect
that it may have something to do with actions vs aliases. I'm a bit busy
until tomorrow evening, so I would recommend Terence to let Vinay take a
look in the meantime.

**Comment by TerencedzLi** [comment]
Hi @vhmth , I've invited you to my test repo! Any help is much appreciated!

And thanks @AgrimPrasad for the help so far!

**Comment by CrustyJew** [comment]
I may have run in to this same issue, it appears you cannot dispatch async actions (thunks) **from** a content script **to** the background page, which makes sense as it relies on the messaging framework which means that the messages passed have to be serializable to json.

What you'd need to do is intercept the action with an alias and then dispatch the async action on the background page itself.

**Comment by vhmth** [comment]
@TerencedzLi left a video for ya - only showed the `event.js` and popup `index.js` scripts - so no worries I haven't exposed all your code! I noticed that the code was taken from the examples repo @tshaddix set up, so I figured the codebase structure wouldn't give much away of what you're working on either. Let me know if you want me to take this video down though!

https://www.useloom.com/share/7edf09825bf14e8f9b4c93fdc201290d

Here's a link to [aliases](https://github.com/tshaddix/react-chrome-redux#3-optional-implement-actions-whose-logic-only-happens-in-the-background-script-we-call-them-aliases) in the README.

@tshaddix I think we discussed potentially allowing other middleware to be applied to the proxy stores. I don't remember if this is currently possible.

**Comment by TerencedzLi** [comment]
@vhmth Nope, no worries there. Thanks for taking a look at it and providing a solution!

 I've been trying to use aliases for a while, and this might be outside the scope of this repo, but do you have suggestions on how to debug the flow of an action being called in a content-script, and then allowing the background to break in devtools in the alias? I'm just trying to see if it works, but I'm having trouble setting up a proper dev/ debugging environment. 

i.e Calling an action in content-script -> sending action to alias in background.js -> break/debug in aliases.js (where aliases are kept).

**Comment by vhmth** [comment]
https://www.useloom.com/share/d84d7a5633fa49778b432f17c6477f16

**Comment by godd9170** [comment]
I'm pretty stuck here too. S'far as I can tell I'm doing everything as per the README dictates, and it seems like my alias is indeed dispatched, but in the `background.js` inspector I get the dirty:

```js
AUTHING IN ALIAS
Error: Actions must be plain objects. Use custom middleware for async actions.
```

```js
//background.js
import { alias, wrapStore} from 'react-chrome-redux';
import { createStore, applyMiddleware } from 'redux';
import reduxThunk from 'redux-thunk';
import reducers from '../reducers';
import { authenticateUser } from '../actions';

//aliases
const aliases = {
  'authenticate-user-alias': () => {
    authenticateUser();
    console.log('AUTHING IN ALIAS'); //<----Makes it to here
  }
};


//Set up store
const store = createStore(reducers,
  applyMiddleware(
    reduxThunk, 
    alias(aliases)
  )
)

wrapStore(store, {portName: 'APP'}); // make sure portName matches 
```

```js
// popup.js
import React from 'react';
import {render} from 'react-dom';
import {Provider} from 'react-redux';
import {Store} from 'react-chrome-redux';

import SignIn from './auth/signin.js';

const store = new Store({
  portName: 'APP' // communication port name
});

store.ready().then(() => {
  render(
    <Provider store={store}>
      <SignIn />
    </Provider>
    , document.getElementById('app'));
});
```

```js
// ./auth/signin.js
import React, { Component } from 'react';
import { connect } from 'react-redux';
class SignIn extends Component {

    constructor(props) {
        super(props);
    }

    login() {
        this.props.authenticateUserAlias();
    }

    render() {
        return (
            <div>
                <button label='Log In' onClick={this.login.bind(this)}/>
            </div>
        );
    }

}

const mapStateToProps = state => ({
    global: state.global,
})

const mapDispatchToProps = dispatch => ({
    authenticateUserAlias() {
      dispatch({ type: 'authenticate-user-alias' });
    }
})

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(SignIn)
```

I'm inclined to believe it's either something wrong in the `mapDispatchToProps` in my signin component. or me not fully understanding how `applyMiddleware` works.

**Comment by CrustyJew** [comment]
It looks like your Middleware is applied in the wrong order. Load aliases
first, then thunk and see if that works

On Mar 29, 2017 10:52 PM, "Henry Goddard" <notifications@github.com> wrote:

I'm pretty stuck here too. S'far as I can tell I'm doing everything as per
the README dictates, and it seems like my alias is indeed dispatched, but
in the background.js inspector I get the dirty:

AUTHING IN ALIASError: Actions must be plain objects. Use custom
middleware for async actions.

//background.jsimport { alias, wrapStore} from
'react-chrome-redux';import { createStore, applyMiddleware } from
'redux';import reduxThunk from 'redux-thunk';import reducers from
'../reducers';import { authenticateUser } from '../actions';
//aliasesconst aliases = {
  'authenticate-user-alias': () => {
    authenticateUser();
    console.log('AUTHING IN ALIAS'); //<----Makes it to here
  }
};

//Set up storeconst store = createStore(reducers,
  applyMiddleware(
    reduxThunk,
    alias(aliases)
  )
)
wrapStore(store, {portName: 'APP'}); // make sure portName matches

// popup.jsimport React from 'react';import {render} from
'react-dom';import {Provider} from 'react-redux';import {Store} from
'react-chrome-redux';
import SignIn from './auth/signin.js';
const store = new Store({
  portName: 'APP' // communication port name
});
store.ready().then(() => {
  render(
    <Provider store={store}>
      <SignIn />
    </Provider>
    , document.getElementById('app'));
});

// ./auth/signin.jsimport React, { Component } from 'react';import {
connect } from 'react-redux';class SignIn extends Component {

    constructor(props) {
        super(props);
    }

    login() {
        this.props.authenticateUserAlias();
    }

    render() {
        return (
            <div>
                <button label='Log In' onClick={this.login.bind(this)}/>
            </div>
        );
    }

}
const mapStateToProps = state => ({
    global: state.global,
})
const mapDispatchToProps = dispatch => ({
    authenticateUserAlias() {
      dispatch({ type: 'authenticate-user-alias' });
    }
})
export default connect(
  mapStateToProps,
  mapDispatchToProps
)(SignIn)

I'm inclined to believe it's either something wrong in the
mapDispatchToProps in my signin component. or me not fully understanding
how applyMiddleware works.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tshaddix/react-chrome-redux/issues/70#issuecomment-290295084>,
or mute the thread

**Comment by godd9170** [comment]
@CrustyJew I've tried that and unfortunately it doesn't seem to make a difference. Thanks though!

**Comment by CrustyJew** [comment]
Hmm well it still should be in that order technically. But if it's still
not working, it may be what your auth action is doing inside your alias. If
it is an async action, you need to change your alias to accept an argument
of "dispatch" so thunk will pick it up. You can check out the dev branch of
my repo called "snoonotes" to see some working example code

On Mar 29, 2017 11:07 PM, "Henry Goddard" <notifications@github.com> wrote:

@CrustyJew <https://github.com/CrustyJew> I've tried that and unfortunately
it doesn't seem to make a difference. Thanks though!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/tshaddix/react-chrome-redux/issues/70#issuecomment-290296789>,
or mute the thread

**Comment by godd9170** [comment]
So I've actually tried simply doing a `console.log` and no actions at and it still tosses that middleware error.

**Comment by TerencedzLi** [comment]
Hey @godd9170 ,

I was so annoyed with those messages too. Not sure which babel preset you're using or if that even matters, but I noticed I wasn't getting the default module from thunk unless I did:
`import * as thunk from 'redux-thunk';`

and then in the `applyMiddleware(aliases(yourAliases), thunk.default)`

And what do you mean by 

> doing a console.log and no actions at and

**Comment by godd9170** [comment]
Hey @TerencedzLi,
I tried your suggestion, and I'm still getting the same errors.

As for my statement `doing a console.log and no actions at and` I mean just doing this in the aliases:

```js
//aliases
const aliases = {
  'authenticate-user-alias': () => {
    //authenticateUser();
    console.log('AUTHING IN ALIAS'); //<----Makes it to here
  }
};
```

**Comment by CrustyJew** [comment]
Couple things to try, first off, this works for me:

```javascript
[REDIRECT_SUCCESS]: (req)=>{
return (dispatch)=>{
userManager.signinRedirectCallback(req.payload).then((user)=>{
let state = store.getState();
chrome.tabs.update(state.user.last_tab_id, {active:true},()=>{
chrome.tabs.remove(req._sender.tab.id);
});
dispatch(userFound(user));
dispatch(getModSubs());
},(err)=>{console.warn(err)});
}
}
```
So, first, for your alias function, add a param for the action, and then
second, try returning either another action object, or an async fynction
for thunk


On Mar 29, 2017 11:22 PM, "Henry Goddard" <notifications@github.com> wrote:

Hey @TerencedzLi <https://github.com/TerencedzLi>,
I tried your suggestion, and I'm still getting the same errors.

As for my statement doing a console.log and no actions at and I mean just
doing this in the aliases:

//aliasesconst aliases = {
  'authenticate-user-alias': () =>
 {
    //authenticateUser();

    console.log('AUTHING IN ALIAS'); //<----Makes it to here
  }
};

—

You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tshaddix/react-chrome-redux/issues/70#issuecomment-290298618>,
or mute the thread

**Comment by godd9170** [comment]
@CrustyJew  what's `[REDIRECT_SUCCESS]:` ? Are you saying do something like:

```js
//aliases
const aliases = {
  'authenticate-user-alias': (req) => {
    return (dispatch) => {
      authenticateUser();
      console.log('AUTHING IN ALIAS'); //<----Makes it to here
    }
  }
};
```

**Comment by CrustyJew** [comment]
Exactly. Then try returning an action object next too and comment out the
auth method you have there

**Comment by CrustyJew** [comment]
The [REDIRECT_SUCCESS] part is just the string constant I'm using for the
alias name.

Holy christ i just saw gmail is mangling these responses to github.  I'll
have to edit those tomorrow....

**Comment by godd9170** [comment]
I've tried both and can't seem to get either to work. By `action object` do you just mean a good old fashioned synchronous action like:

```js
export const setToken = (token) => ({ type: types.SET_TOKEN, token })
```

**Comment by CrustyJew** [comment]
Yeah have your alias return {type:"someaction"}

**Comment by godd9170** [comment]
This is what my working alias ended up looking like

```js
//aliases
const aliases = {
  'authenticate-user-alias': authenticateUser
};
```

Damn ECMAscript throws me off yet again. One day I'll understand it.

Thanks @CrustyJew and @TerencedzLi

**Comment by tshaddix** [comment]
@TerencedzLi Has your issue been resolved?

**Comment by TerencedzLi** [comment]
Yup!

**Comment by tshaddix** [comment]
@TerencedzLi Nice!

**Comment by vhmth** [comment]
👋🏾  y'all. Been super busy so just catching up on this now (yikes). @TerencedzLi you should be able to do:

```
import thunk from 'redux-thunk';

// ... some more imports and other stuff

const middleware = [
  alias(aliases),
  thunk,
  logger
];

const store = createStore(reducer, applyMiddleware(...middleware));
```

**Comment by Nishchit14** [comment]
@vhmth 
I'm following the same but thunk-action goes into infinite loop. 
It's printing `In thunk` in console on every 5 sec

```
export function fetchOpenTabs() {

    return dispatch => {

        setTimeout(()=>{
            console.log("In thunk");
            console.log(new Date());
            dispatch({
		type : 'GET_ALL_OPEN_TABS',
		data : []
	    })
        }, 5000)
    }
}
```
```
const aliases = {

    'GET_ALL_OPEN_TABS' : () => {
       return fetchOpenTabs()
     }
};
let middleware = [
  alias(aliases),
  thunk,
  logger]

let store = createStore(rootReducer, applyMiddleware(...middleware))

export default store;
```

OUTPUT
![image](https://user-images.githubusercontent.com/5078921/27854813-c5af3184-6185-11e7-8a9e-4fd4b0c1f6eb.png)

Am I doing wrong anything? @TerencedzLi @vhmth

**Comment by Nishchit14** [comment]
Okay I found the issue, 
I have the same **ALIAS** name and **ACTION** name. That's why it went to the infinite loop.

now I change the name like
Alias:  `alias@GET_ALL_OPEN_TABS`
Action: `GET_ALL_OPEN_TABS`

**Comment by vhmth** [comment]
Strange. I *really* feel like there should be a better way to revamp aliases, but I still can't for the life of me wrangle my head around it. I suppose it would help to write down all the pitfalls right now and then see if I can figure out a solution that tries to address all or most of them.

**Comment by tshaddix** [comment]
@Nishchit14 ah this makes sense. When you're using an alias, it's really just [re-injecting the new action into the pipeline](https://github.com/tshaddix/react-chrome-redux/blob/master/src/alias/alias.js#L10). When you do this, the middleware will actually run again on this new action. Since it has the same name, it will alias it again and forever the loop will go. I never did discover why this happens with redux middleware logic but it is definitely a known issue.
