### ISSUE TITLE
Only process dispatches for your port

### ISSUE THREAD

**Issue by collinsauve** [tshaddix/react-chrome-redux#71]
If I have 2 different stores running in the background page, a dispatch to one of them will be handled by all stores - the reducers will run, the state will flow out to all connected ports, and proxy stores will fire registered subscribers.

I propose that dispatch messages include a `port` property, and when receiving them it will only be processed if `request.port === portName`.

**Comment by vhmth** [comment]
Great catch

**Comment by tshaddix** [comment]
Interesting @collinsauve. Makes sense. We wrap all communication in `react-chrome-redux` types but this only gets you halfway if you're running multiple stores (as you've discovered).

So essentially we're just tagging the request with some agreed-upon key, and it's easy to use `portName` as that key because it is both unique, known to both the proxy and the event page, and doesn't change the API. Did I get that right?

The reasoning seems sound. I'm going to nitpick at calling the key `port` instead of `portName`, but I'll do that on the PR :)

Great catch!

**Comment by collinsauve** [comment]
@tshaddix yup, you've got that all correct.
