### ISSUE TITLE
Question: Usage of dispatchResponder

### ISSUE THREAD

**Issue by collinsauve** [tshaddix/react-chrome-redux#82]
I see a question about usage of alias and dispatchResponder on #26, which was closed on #27... however that PR only includes documentation for alias - and not dispatchResponder.

Can someone explain the purpose/usage of dispatchResponder for me, and/or document it in README?

**Comment by tshaddix** [comment]
Does this help? https://github.com/tshaddix/react-chrome-redux/wiki/Advanced-Usage#dispatchresponder

**Comment by collinsauve** [comment]
Hah! Somehow when searching I managed to find the other issue, but not that wiki doc :(

Thanks!

**Comment by tshaddix** [comment]
@collinsauve No worries!

**Comment by fantasticole** [comment]
Another piece of potentially relevant information:

```js
export const proxyStore =  new Store({
  state: {},
  portName: 'tagmarker'
});

const unsubscribe = proxyStore.subscribe(() => {
   unsubscribe(); // make sure to only fire once
  console.log('proxyStore:', proxyStore)
   render(
    <Provider store={proxyStore}>
      <Drawer/>
    </Provider>
    , document.getElementById('tags'));
});
```
When I try to log the value of `proxyStore` here, it has no `dispatchResponder` key:
```js
{
   dispatch : ƒ (),
   extensionId : "",
   listeners : [],
   port : Port {},
   portName : "tagmarker",
   readyPromise : Promise {<pending>},
   readyResolve : ƒ (),
   readyResolved : false,
   state : {data: {…}},
}
```

**Comment by fantasticole** [comment]
@tshaddix is this the appropriate place to ask this question or should I repost somewhere else? Thanks!

**Comment by vhmth** [comment]
Hey @fantasticole - if you look at the code, that's actually because the dispatch responder (responding to dispatched actions from the content script) is actually implemented on the background store (wrap store):

https://github.com/tshaddix/react-chrome-redux/blob/master/src/wrap-store/wrapStore.js#L15

May I ask what your use case is for using this component directly?

**Comment by fantasticole** [comment]
Thanks for getting back to me, @vhmth! In my first comment I shared my implementation, including these lines from my `background.js` file:
```js
wrapStore(store, {
  portName: 'tagmarker',
  dispatchResponder: reduxPromiseResponder,
});
```
Is this incorrect?

My use case has changed but this would still be helpful, as I want to make sure an api request in an action has finished before doing something in my component.

**Comment by vhmth** [comment]
Yep that should be correct (at least looking at the code). I was more commenting on the fact that you won't see that responder in the proxy store (responding to `When I try to log the value of proxyStore here, it has no dispatchResponder key:`) because the responder is implemented on the wrapped store in the background page. Not sure if that's the issue here, but that was the first thing I noticed!

**Comment by fantasticole** [comment]
Ah, ok. That makes sense! But I should be able to run `.then()` after my action dispatched from the proxy store, shouldn't I? Or am I misunderstanding how this works?

**Comment by vhmth** [comment]
Hmm that's a good question. cc @tshaddix - should we implement something like this? Seems useful! On the other hand, I can think of a case to be made where you wouldn't want to chain `.then`s from the content/popup scripts. It seems like that's typically reserved for action creators, which in react-chrome-redux's case are aliases that run on the background script.
