### ISSUE TITLE
Can react-chrome-redux be used for apps?

### ISSUE THREAD

**Issue by mtwallet** [tshaddix/react-chrome-redux#9]
Hi All,

Apologies if this is a dumb question as I'm new to Google App/Extension development. I'm trying to create a kiosk application to run on a Chromebit. Can react-chrome-redux be used for apps rather extensions? With my limited knowledge there appears to be some differences between the two. My application currently is a simple React Redux app that uses Redux Thunk to fetch data from a rest api.

If this is possible I'd really appreciate some pointers.

Many thanks in advance.

**Comment by tshaddix** [comment]
Hi, @mtwallet!

I have never used this package in a chrome app, but I believe you should be just fine. The only chrome api `react-chrome-redux` uses is the `chrome.runtime` API, which should be available to your app's background and window pages.

Please feel free to correct me if this turns out to be false!
