### ISSUE TITLE
Do redux dev tools work?

### ISSUE THREAD

**Issue by SudoPlz** [tshaddix/react-chrome-redux#96]
Hi,

I tried:

	import { createStore, applyMiddleware } from 'redux';
	import { wrapStore } from 'react-chrome-redux';

	import rootReducer from './reducers';
	import { youtubeMasterConfig } from '../../package.json';

	const store = createStore(
	    rootReducer,
	    {}, 
	    window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
	);

	wrapStore(store, {
	  portName: youtubeMasterConfig.portName,
	});

but I don't seem to be able to see any events in the chrome dev tools extension.

Any ideas?

thanks!

**Comment by vhmth** [comment]
@SudoPlz it seems like you're doing this in the background, mind posting in #78? Will close for now since your issue seems to be related, but feel free to reopen if that's not the case! When you do post there, it might be useful to attach a video showing what you're seeing. For that, you can use [Loom](https://www.useloom.com). I'm trying to be as unbiased as possible here, but our tool is the easiest way to show others what you're seeing. :-P

**Comment by SudoPlz** [comment]
Oh yeah it's the same, issue, thanks.

**Comment by vhmth** [comment]
For sure!
